# Generated by Django 5.0.7 on 2024-08-12 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["-date_joined"]},
        ),
    ]
