# Generated by Django 5.0.7 on 2024-08-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
