# Generated by Django 5.0.7 on 2024-08-21 05:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0003_customuser_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uid",
            field=models.CharField(
                default=uuid.UUID("2d50b4ec-5f81-11ef-95cb-acde48001122"),
                max_length=1000,
            ),
        ),
    ]
