# Generated by Django 5.0.7 on 2024-08-21 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0004_customuser_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uid",
            field=models.CharField(
                default=uuid.UUID("a4b0c540-5f81-11ef-be97-acde48001122"),
                max_length=1000,
            ),
        ),
    ]
